language: python # Set the build language to Python

python: 3.7.2 # Set the version of Python to use

branches: 107 # Set the branch to build from

install:
    - pip install mkdocs # Install the required dependencies
    - pip install mkdocs-material # Install the required dependencies

script:
    - mkdocs build --verbose --clean # Build a local version of the docs

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $github_token  # Set in the settings page of your repository, as a secure variable
  local-dir: site
  keep-history: true
  target-branch: gh-pages
  verbose: true
  on:
    branch: 107

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true