language: python # Set the build language to Python

python: 3.6 # Set the version of Python to use

branches: 107 # Set the branch to build from

install:
    - pip install mkdocs==0.17.3 # Install the required dependencies
    - pip install mkdocs-material==2.7.3 # Install the required dependencies

before_deploy:
    - mkdocs build --verbose --clean --strict # Build a local version of the docs

after_success:
  - git config user.name "Anton Yip";
  - git config user.email "hello@antonyip.com";
  - git remote add gh-token "https://${github_token}@github.com/antonyip/aragon-wiki.git";
  - git fetch gh-token && git fetch gh-token gh-pages:gh-pages;
  - mkdocs gh-deploy -v --clean --remote-name gh-token;