language: python # Set the build language to Python

python: 3.5 # Set the version of Python to use

branches: 107 # Set the branch to build from

install:
    - pip install mkdocs==0.17.3 # Install the required dependencies
    - pip install mkdocs-material==2.7.3 # Install the required dependencies

script:
    - mkdocs build --verbose --clean --strict # Build a local version of the docs

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $github_token  # Set in the settings page of your repository, as a secure variable
  local-dir: site
  keep-history: true
  target-branch: gh-pages
  verbose: true
  on:
    branch: 107
